replicas: 2

service:
  type: LoadBalancer
  client:
    port: 2379
  peer:
    port: 2380

storage:
  requestedSize: 2Gi

settings:
  https:
    enabled: false
rbac:
  create: false

serviceAccount:
  create: false
